name: Deploy to HuggingFace Spaces

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote add space https://ezms:$HF_TOKEN@huggingface.co/spaces/ezms/roster-api
          git push space $(git subtree split --prefix=api main):main --force
